<SampGridLayout>:
    rows:2

    BoxLayout:
        size_hint_y: None
        height: 30
        spacing: 10

        canvas:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                pos: self.pos
                size: self.size

        Button:
            background_normal: 'black'
            background_down: 'white'
            size_hint_x: None
            width: 30